# Generated by Django 3.0.1 on 2020-12-09 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onwer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Onwer_name', models.CharField(max_length=128)),
                ('Onwer_contact_number', models.IntegerField()),
                ('Onwer_address', models.TextField(max_length=500)),
                ('Onwer_ID', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_name', models.CharField(max_length=128)),
                ('Organization_ragistration_number', models.CharField(max_length=128)),
                ('Organization_contact_number', models.BigIntegerField()),
                ('Organization_address', models.TextField(max_length=500)),
                ('Organization_number_of_employee', models.IntegerField(default=0)),
                ('Established_date', models.DateField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 12, 9, 17, 9, 29, 263586, tzinfo=utc))),
                ('Owner_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearningApp.Onwer')),
            ],
        ),
    ]
